// Fly Box — the compiled content, plus the lookups the UI needs.
// bundle.json is generated by `node content/build.mjs`. Never edit it.

import bundle from './bundle.json';

export { bundle };

/**
 * Content stores image paths as "assets/gotcha.jpg". A bare relative src is
 * resolved against the CURRENT url, so it breaks the moment you are at
 * /Fly-Box without a trailing slash. Build it off the configured base instead.
 */
export const assetUrl = (path) =>
  (path ? import.meta.env.BASE_URL.replace(/\/?$/, '/') + String(path).replace(/^\//, '') : null);

export const nameOf = (table, id) => bundle.byId[table]?.[id]?.name ?? id;
export const record = (table, id) => bundle.byId[table]?.[id] ?? null;

export const regions = bundle.tables.regions;
export const speciesList = bundle.tables.species;
export const flies = bundle.tables.flies;
export const organisms = bundle.tables.organisms;
export const rigs = bundle.tables.rigs;
export const materials = bundle.tables.materials ?? [];

/**
 * The bench sheet for one leader — cut list, junction turns, spools, IGFA
 * limits. Computed by content/leader.mjs at build time, so the phone is only
 * ever reading an answer.
 */
export const leaderSheet = (rigId) => bundle.leaderSheets?.[rigId] ?? null;
export const knots = bundle.tables.knots;
export const concepts = bundle.concepts;

/**
 * The concept ids a deck holds. Membership ships as indexes into `concepts`
 * (see content/build.mjs), so this is where they turn back into ids. `key` is a
 * deck id, a region id, or "<region>.<species>" for a trip.
 */
export const deckMembers = (key) => {
  const idx = bundle.index.deckConcepts?.[key] ?? bundle.index.tripDecks?.[key];
  if (!idx) return null;
  const out = new Set();
  for (const i of idx) { const c = bundle.concepts[i]; if (c) out.add(c.id); }
  return out;
};

export const speciesIn = (regionId) =>
  bundle.tables.species.filter((s) => s.regions?.includes(regionId));

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/** Reviewed-vs-draft, so the app can be honest about its own confidence. */
export const confidence = () => {
  const total = Object.values(bundle.counts).reduce((a, b) => a + b, 0);
  const reviewed = Object.values(bundle.reviewed).reduce((a, b) => a + b, 0);
  return { total, reviewed, draft: total - reviewed };
};
