// Fly Box — the compiled content, plus the lookups the UI needs.
// bundle.json is generated by `node content/build.mjs`. Never edit it.

import bundle from './bundle.json';

export { bundle };

export const nameOf = (table, id) => bundle.byId[table]?.[id]?.name ?? id;
export const record = (table, id) => bundle.byId[table]?.[id] ?? null;

export const regions = bundle.tables.regions;
export const speciesList = bundle.tables.species;
export const flies = bundle.tables.flies;
export const organisms = bundle.tables.organisms;
export const rigs = bundle.tables.rigs;
export const knots = bundle.tables.knots;
export const concepts = bundle.concepts;

export const speciesIn = (regionId) =>
  bundle.tables.species.filter((s) => s.regions?.includes(regionId));

export const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/** Reviewed-vs-draft, so the app can be honest about its own confidence. */
export const confidence = () => {
  const total = Object.values(bundle.counts).reduce((a, b) => a + b, 0);
  const reviewed = Object.values(bundle.reviewed).reduce((a, b) => a + b, 0);
  return { total, reviewed, draft: total - reviewed };
};
